### ISSUE TITLE
Updated architecture document based on Phil's diagram

### ISSUE THREAD

**Issue by stain** [federated-analytics/technical-roadmap#24]
*  to complete [Architecture Document](https://docs.google.com/document/d/1K6BX94iHXgxpTDCNwVgkKoNodaZBoufqUu2VcAZmdLU/edit#heading=h.6x17gwaf87a1)

Phil's diagram: https://app.diagrams.net/#G17TO-2VH-59Pm8FMenrYBpN8xAnI-PfGI#%7B%22pageId%22%3A%224bL5o4j64XjnUdqXuRuk%22%7D

![diagram](https://github.com/federated-analytics/technical-roadmap/assets/253413/269a943d-b82e-4981-854c-d5c5fcaf1f5d)

As discussed in [Manchester technical roadmap meeting](https://docs.google.com/document/d/1Y6VcYo1IQSErZdXnUib4YRnK83StRU1CxHt0-aj6PVM/edit#heading=h.oh2urbm14z1v).

**Comment by stain** [comment]
https://docs.google.com/document/d/1K6BX94iHXgxpTDCNwVgkKoNodaZBoufqUu2VcAZmdLU/edit was started but not filled in

**Comment by stain** [comment]
Architecture requirements for "Cratey" is in #16

**Comment by ianhinder** [comment]
Blocked by #16.

**Comment by ianhinder** [comment]
@stain to chase with Tim.

**Comment by alexhambley** [comment]
![Image](https://github.com/user-attachments/assets/f1b7b020-3105-4581-8543-332360e067b9)
